iplan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

#path('planner/', include('planner.urls')),
urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('', include('planner.urls')),
    path('planner/login/', auth_views.LoginView.as_view(template_name='planner/login.html', redirect_field_name=''), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

planner/urls.py
from django.urls import path
from planner.views import github_login, login_request, github_callback, IndexView, PersonDetailView, PersonListView, TaskListView, MeetingListView, PersonUpdateView, BioUpdateView, EmailUpdateView, PersonDetailUpdateView, TaskUpdateView, MeetingUpdateView, TaskDeleteView, TaskCreateView, MeetingDeleteView, MeetingCreateView, logout_request, ContactView, ThanksView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

# used for namespacing URL names
# https://docs.djangoproject.com/en/3.1/intro/tutorial03/#namespacing-url-names
app_name = 'planner'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('person/<int:pk>/', PersonDetailView.as_view(), name='person_detail'),
    path('people/', PersonListView.as_view(), name='people_list'),
    path('person/tasks/<int:pk>/', TaskListView.as_view(), name='task_list'),
    path('person/meetings/<int:pk>/', MeetingListView.as_view(), name='meeting_list'),
    path('person/edit/<int:pk>/', PersonUpdateView.as_view(), name='person_update_form'),
    path('bio/edit/<int:pk>/', BioUpdateView.as_view(), name='bio_update_form'),
    path('email/edit/<int:pk>/', EmailUpdateView.as_view(), name='email_update_form'),
    path('person/<int:pk>/edit', login_required(PersonDetailUpdateView.as_view()), name='person_detail_update_form'),
    path('task/<int:pk>/edit', TaskUpdateView.as_view(), name='task_update_form'),
    path('meeting/<int:pk1>/person/<int:pk2>/edit', MeetingUpdateView.as_view(), name='meeting_update_form'),
    path('task/<int:pk>/delete', TaskDeleteView.as_view(), name='task_confirm_delete'),
    path('task/<int:pk>/create', TaskCreateView.as_view(), name='task_create_form'),
    path('meeting/<int:pk1>/person/<int:pk2>/delete', MeetingDeleteView.as_view(), name='meeting_confirm_delete'),
    path('meeting/<int:pk>/create', MeetingCreateView.as_view(), name='meeting_create_form'),
    path('logout/', logout_request, name='logout'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('thanks/<str:visitor>/<int:success>', ThanksView.as_view(), name='thanks'),
    path('login_request/', login_request, name='login_request'),
    path('github_login/', github_login, name='github_login'),
    path('github_callback/', github_callback, name='github_callback'),
]

planner/models.py
from django.db import models
from datetime import date, timedelta, datetime
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from dateutil.parser import parse

# Person has one-to-many relationship with Task & Meeting
# Person has one-to-one relationship with Email
class Person(models.Model):
    STATUS = [
        ('AWAY', 'I am away'),
        ('BUSY', 'I am busy'),
        ('MEETING', 'I am in a meeting'),
        ('IDLE', 'I am available')
    ]

    # define attributes here
    name = models.CharField(max_length=20)
    status = models.CharField(max_length=10, choices=STATUS, default='IDLE')
    age = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    # define metadata here
    class Meta:
        verbose_name_plural = 'people'

    # define methods here
    def get_absolute_url(self):
        return reverse('planner:person_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def all_task_count(self):
        # return the number of tasks for this person
        self.tasks_count = self.task_set.count()
        return self.tasks_count

    def all_meeting_count(self):
        # return the number of meetings for this person
        return self.meeting_set.count()

    # return all tasks
    def all_tasks(self):
        return self.task_set.all()

    # return all expired tasks
    def expired_tasks(self):
        return self.task_set.filter(deadline__lt=date.today())

    # return all tasks due today
    def tasks_due_today(self):
        return self.task_set.filter(deadline=date.today())

    # return all pending tasks
    def pending_tasks(self):
        return self.task_set.filter(deadline__gte=date.today()).order_by('deadline', 'title')

    # return all future tasks
    def future_tasks(self):
        return self.task_set.filter(deadline__gt=date.today()).order_by('deadline', 'title')

    # return all meetings scheduled for today
    def meetings_today(self):
        return self.meeting_set.filter(participants__name=self.name).filter(date=date.today())

    # return all incoming meetings for today, including those happening now
    def incoming_meetings_today(self):
        return self.meeting_set.filter(participants__name=self.name).filter(date=date.today()).filter(time__gte=datetime.now())

    # return all future meetings beyond today
    def future_meetings(self):
        return self.meeting_set.filter(participants__name=self.name).filter(date__gt=date.today())

    # return all expired meetings
    def expired_meetings(self):
        return self.meeting_set.filter(participants__name=self.name).filter(date__lt=date.today())

    def my_status(self):
        # if I'm in a meeting right now, status='MEETING'
        # compare current time with end of meeting time
        meetings = self.meetings_today()
        for meeting in meetings:
            start_time = datetime.combine(meeting.date,meeting.time)
            end_time = timedelta(minutes=meeting.duration) + start_time
            time_now = datetime.now()
            if time_now.time() > start_time.time() and time_now.time() < end_time.time():
                self.status = 'MEETING'
                self.save()
                return self.status

        # if I've tasks due today, status='BUSY'
        if self.status != 'AWAY' and len(self.tasks_due_today()):
            self.status = 'BUSY'
            self.save()

        return self.status

# Bio has a one-to-one relationship with Person, but can be NULL
class Bio(models.Model):
    # define attributes here
    bio = models.TextField()
    image = models.URLField()
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    # define methods here
    def __str__(self):
        return self.bio

    # define methods here
    def get_absolute_url(self):
        return reverse('planner:person_detail', kwargs={'pk': self.pk})



# Email has one-to-one relationship with Person
class Email(models.Model):
    # define attributes here
    address = models.EmailField(verbose_name='Email')
    person = models.OneToOneField(Person, on_delete=models.CASCADE)

    # override the Manager attribute
    # instances = models.Manager()

    # define metadata here

    # define methods here
    def __str__(self):
        return self.address

    # define methods here
    def get_absolute_url(self):
        return reverse('planner:person_detail', kwargs={'pk': self.pk})

# Task has many-to-one relationship with Person
class Task(models.Model):
    # define attributes here
    title = models.CharField(max_length=30)
    description = models.TextField()
    deadline = models.DateField(default=timezone.now)
    person = models.ForeignKey(Person, on_delete=models.CASCADE,null=True)

    # define metadata here
    ordering = ['deadline', 'title']

    # define methods here
    def __str__(self):
        return ("%s, %s, %s, %s\n" %(self.person, self.title, self.description, self.deadline.strftime('%c')))

    # define methods here
    def get_absolute_url(self):
        return reverse('planner:person_detail', kwargs={'pk': self.person.pk})

# Meeting has many-to-many relationship with Person
# Meeting also has a meny-to-one relationship 'created_by' with Person
class Meeting(models.Model):
    # define attributes here
    title = models.CharField(max_length=30)
    purpose = models.TextField()
    date = models.DateField(default=timezone.now)
    time = models.TimeField()  #default=datetime.now()
    created_by = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='created_by')

    # duration of meeting in number of minutes
    duration = models.IntegerField(default=30)

    # the participants in the meeting
    participants = models.ManyToManyField(Person)

    # define metadata here
    class Meta:
        ordering = ['date', 'time']

    # define methods here
    def __str__(self):
        return '%s, %s, %s, %s, %s with %s' %(self.title, self.purpose, self.date.strftime('%a'), self.date, self.time, self.participants.all())

    # return participant count
    def participant_count(self):
        return self.participants.count()

planner/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from planner.models import Person, Email, Bio, Meeting, Task
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
from iplan import settings
from captcha.fields import CaptchaField
from django.urls import reverse
import smtplib
from dotenv import dotenv_values

# This form is used in PersonDetailUpdateView in views.py
class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = '__all__'
        fields = ['name', 'status', 'age']
        

# This form is used in PersonDetailUpdateView in views.py
class EmailForm(ModelForm):
    class Meta:
        model = Email
        # fields = '__all__'
        fields = ['address']

# This form is used in PersonDetailUpdateView in views.py
class BioForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].disabled = True

    class Meta:
        model = Bio
        # fields = '__all__'
        fields = ['bio', 'image']

'''
This form is used in
MeetingUpdateView and MeetingDeleteView
in views.py
'''
class MeetingForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['created_by'].disabled = True

    class Meta:
        model = Meeting
        fields = '__all__'
        #fields = ['title', 'purpose', 'date', 'time', 'participants']
        widgets = {
            'date': forms.DateInput(attrs={'class':'datepicker'}),
            'time': forms.TimeInput(attrs={'class':'timepicker'}),
        }

# This form is used in TaskCreateView in views.py
class TaskForm(ModelForm):
    class Meta:
        model = Task
        #fields = '__all__'
        fields = ['title', 'description', 'deadline']
        widgets = {
            'deadline': forms.DateInput(attrs={'class':'datepicker'}),
        }

# This form is used in ContactView in views.py
class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    linkedin = forms.URLField(label='LinkedIn profile', initial='http://linkedin.com/in/')
    subject = forms.CharField(initial='Request a Demo account')
    message = forms.CharField(widget=forms.Textarea, initial="Hi, I'd like to test out this demo, thanks.")
    captcha = CaptchaField()

    def send_email(self):
        origin = settings.SITE_URL + reverse('planner:contact')
        subject = '[ContactForm] from %s' %origin
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        linkedin = self.cleaned_data['linkedin']
        message = self.cleaned_data['message']
        body = """
        Name: %s
        Email: %s
        LinkedIn: %s
        Content: %s
        """ %(name, email, linkedin, message)
        sender = settings.EMAIL_HOST_USER
        receipient = 'djangomail@djangodemo.com'
        
        response = 0

        try:
            response = send_mail(
                subject,
                body,
                sender,
                [receipient],
                fail_silently=False,
                #auth_user='bad_user',
            )
        except smtplib.SMTPException:
            #assert False
            pass

        return response

planner/templates/planner/base.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <!--
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
    -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      body, h1, h2, h3, h4, h5, h6  {
        font-family: Roboto, sans-serif;
      }
      .w3-sofia {
        font-family: Sofia, cursive;
      }
    </style>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css"> 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   
    <script 
      src="https://code.jquery.com/jquery-1.12.4.min.js" 
      integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
      crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
      integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
      crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script src="{% static 'js/iplan.tabs.js' %}"></script> 
    <script src="{% static 'js/iplan.init.js' %}"></script> 
    <script src="https://kit.fontawesome.com/17c2082d4f.js" crossorigin="anonymous"></script>
    <title>
      {% block title %}
        {{ title }}
      {% endblock title %}
    </title>

  </head>
  <body>
 
  <!-- Top Navigation -->
  <div class="w3-top">
    <div class="w3-bar w3-theme-light w3-border">
      <div class="w3-dropdown-hover w3-hide-medium w3-hide-large">
        <button class="w3-button w3-theme"><i class="fa fa-bars"></i></button>
        <div class="w3-dropdown-content w3-bar-block">
          <a href="{% url 'planner:people_list' %}" class="w3-bar-item w3-button w3-border-bottom">Directory</a>
          <a href="{% url 'planner:contact' %}" class="w3-bar-item w3-button w3-border-bottom">Contact Us</a>
        </div>
      </div>
      <a href="{% url 'planner:index' %}" class="w3-bar-item w3-button w3-border-right">Home</a>
      <a href="{% url 'planner:people_list' %}" class="w3-bar-item w3-button w3-border-right w3-hide-small">Directory</a>
      <a href="{% url 'planner:contact' %}" class="w3-bar-item w3-button w3-border-right w3-hide-small">Contact Us</a>

      {% if user.is_authenticated %}
      <div class="w3-left">
      <a href="{% url 'planner:logout' %}" class="w3-bar-item w3-border-right w3-button">Logout </a>
      </div>
      <div class="w3-dropdown-hover w3-right">
        <button class="w3-button w3-pink w3-sofia">Welcome, {{ user.person.name }}!</button>
          <div class="w3-dropdown-content w3-bar-block">
            <a class="w3-bar-item w3-button w3-border-bottom" href="{% url 'planner:person_detail' user.person.pk %}">My Profile</a>
            <a class="w3-bar-item w3-button w3-border-bottom" href="{% url 'planner:task_list' user.person.pk %}">My Tasks</a>
            <a class="w3-bar-item w3-button w3-border-bottom" href="{% url 'planner:meeting_list' user.person.pk %}">My Meetings</a>
          </div>
      </div>
      {% else %}
      <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-border-right">Login </a>
      {% endif %}
    </div>
  </div>
  <div class="w3-main">
    <!-- Header -->
    <div class="w3-theme" style="margin-top:40px">
      <div class="w3-card w3-center w3-sofia">
        <h1 class="w3-sofia">iPlan Demo</h1>
        <p>Django app for planning tasks and meetings</p>
      </div>
    </div>
    <!-- Body -->
    <div class="w3-container w3-responsive w3-text-theme">
      {% if messages %}
      <div class="w3-panel w3-pink w3-display-container">
        <ul class="w3-ul">
        {% for message in messages %}
          <span onclick="this.parentElement.style.display='none'" class="w3-button w3-medium w3-display-topright">&times;</span>
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
      </div>
      {% endif %}
      <!--
      <div id="debug">

      </div>
      -->
      {% block content %}
      {% endblock content %}

    </div>

    <!-- Footer -->
    <div class="w3-theme w3-card w3-center w3-sofia">
      <h1 class="w3-sofia">Designed By</h1>
      <p>&copy; <a href="http://merilynchesler.medium.com">Merilyn Chesler</a>, All Rights Reserved.</p>
    </div>
  </div>
  </body>
</html>

planner/templates/planner/grid_task_list.html
{% extends "planner/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<h2><a href="{% url 'planner:person_detail' person.pk %}">{{ person.name }}</a>'s Tasks</h2>
<p>Today's Date and Time: {{ time_now }}</p>
<div class="w3-row w3-container w3-theme-14 w3-text-theme w3-margin">
  <a href="javascript:void(0)" onclick="openTab(event, 'Task_Today');">
    <div id="Task_TodayTitle" class="w3-quarter tablink w3-bottombar w3-hover-light-grey w3-padding">Today</div>
  </a>
  <a href="javascript:void(0)" onclick="openTab(event, 'Task_Future');">
    <div id="Task_FutureTitle" class="w3-quarter tablink w3-bottombar w3-hover-light-grey w3-padding">Future</div>
  </a>
  <a href="javascript:void(0)" onclick="openTab(event, 'Task_Expired');">
    <div id="Task_ExpiredTitle" class="w3-quarter tablink w3-bottombar w3-hover-light-grey w3-padding">Expired</div>
  </a>
  {% if user.is_authenticated and person.user == user %}
  <a href="javascript:void(0)" onclick="openTab(event, 'Task_New');">
    <div id="Task_NewTitle" class="w3-quarter tablink w3-bottombar w3-hover-light-grey w3-padding">New</div>
  </a>
  {% endif %}
</div>

<div id="Task_Future" class="w3-container w3-margin w3-responsive tab" style="display:none">
    <h3 class="w3-center">Future Tasks</h3>
    <div class="w3-row">
      {% for task in future_page_obj %}
      <div class="w3-container w3-third w3-mobile w3-center">
        <div class="w3-card-4 w3-margin w3-round">
          <header class="w3-container w3-theme-light">
            <h5>{{ task.title }}</h5>
          </header>
          <div class="w3-container">
            <p title="{{ task.description }}">{{ task.description | truncatechars:40 | urlizetrunc:15 }}</p>
          </div>
          <footer class="w3-container w3-pink">
            <h5>{{ task.deadline }}</h5>
          </header>

          {% if user.is_authenticated and person.user == user %}
          <a href="{% url 'planner:task_update_form' task.pk %}">
          <i class='far fa-edit'></i>
          </a>
          
          <a href="{% url 'planner:task_confirm_delete' task.pk %}">
          <i class='far fa-trash-alt'></i>
          </a>
          {% endif %}
        </div>
      </div>
      {% empty %}
      {% endfor %}
    </div>  
  {% if future_page_obj.has_other_pages %}
  <div class="w3-center">
    <div class="w3-bar w3-border w3-round">
      {% if future_page_obj.has_previous %}
        <a class="w3-button" href="?task=future&page=1">&laquo;</a>
        <a class="w3-button" href="?task=future&page={{ future_page_obj.previous_page_number }}">{{ future_page_obj.previous_page_number }}</a>
      {% endif %}
      <a class="w3-button w3-red">{{ future_page_obj.number }}</a>
      {% if future_page_obj.has_next %}
        <a class="w3-button" href="?task=future&page={{ future_page_obj.next_page_number }}">{{ future_page_obj.next_page_number }}</a>
        <a class="w3-button" href="?task=future&page={{ future_page_obj.paginator.num_pages }}">&raquo;</a>
      {% endif %}
    </div>
  </div>
  {% endif %}
</div>


<div id="Task_Today" class="w3-container w3-margin w3-responsive tab">
    <h3 class="w3-center">Tasks Due Today</h3>
    <div class="w3-row">
        {% for task in today_page_obj %}
        <div class="w3-container w3-third w3-mobile w3-center">
          <div class="w3-card-4 w3-round w3-margin">
            <header class="w3-container w3-theme-light">
              <h5>{{ task.title }}</h5>
            </header>
          <div class="w3-container">
            <p title="{{ task.description }}">{{ task.description | truncatechars:40 | urlizetrunc:15 }}</p>
          </div>
          <footer class="w3-container w3-pink">
            <h5>{{ task.deadline }}</h5>
          </footer>
          {% if user.is_authenticated and person.user == user %}
          <a href="{% url 'planner:task_update_form' task.pk %}">
          <i class='far fa-edit'></i>
          </a>
          <a href="{% url 'planner:task_confirm_delete' task.pk %}">
          <i class='far fa-trash-alt'></i>
          </a>
          {% endif %}
          </div>
        </div>
        {% empty %}
        {% endfor %}
    </div>
  {% if today_page_obj.has_other_pages %}
  <div class="w3-center">
    <div class="w3-bar w3-border w3-round">
      {% if today_page_obj.has_previous %}
        <a class="w3-button" href="?task=today&page=1">&laquo;</a>
        <a class="w3-button" href="?task=today&page={{ today_page_obj.previous_page_number }}">{{today_page_obj.previous_page_number}}</a>
      {% endif %}
      {% comment %}
      Page {{ today_page_obj.number }} / {{ today_page_obj.paginator.num_pages }}
      {% endcomment %}
      <a class="w3-button w3-red">{{ today_page_obj.number }}</a>

      {% if today_page_obj.has_next %}
        <a class="w3-button" href="?task=today&page={{ today_page_obj.next_page_number }}">{{today_page_obj.next_page_number}}</a>
        <a class="w3-button" href="?task=today&page={{ today_page_obj.paginator.num_pages }}">&raquo;</a>
      {% endif %}
    </div>
  </div>
  {% endif %}
</div>



<div id="Task_Expired" class="w3-container w3-margin w3-responsive tab" style="display:none">
    <h3 class="w3-center">Expired Tasks</h3>
    <div class="w3-row">
      {% for task in expired_page_obj %}
      <div class="w3-container w3-third w3-mobile w3-center">
        <div class="w3-card-4  w3-round w3-margin">
          <header class="w3-container w3-theme-light">
            <h5>{{ task.title }}</h5>
          </header>
        <div class="w3-container">
          <p title="{{ task.description }}">{{ task.description | truncatechars:40 }}</p>
        </div>
        <footer class="w3-container w3-pink">
          <h5>{{ task.deadline }}</h5>
        </footer>
        {% if user.is_authenticated and person.user == user %}
            <a href="{% url 'planner:task_confirm_delete' task.pk %}" class="w3-button">
            <i class='far fa-trash-alt'></i>
            </a>
        {% endif %}
        </div>
      </div>
      {% empty %}
      {% endfor %}
    </div>
  {% if expired_page_obj.has_other_pages %}
  <div class="w3-center">
    <div class="w3-bar w3-border w3-round">
      {% if expired_page_obj.has_previous %}
        <a class="w3-button" href="?task=expired&page=1">&laquo;</a>
        <a class="w3-button" href="?task=expired&page={{ expired_page_obj.previous_page_number }}">{{ expired_page_obj.previous_page_number }}</a>
      {% endif %}
        <a class="w3-button w3-red">{{ expired_page_obj.number }}</a>
      {% if expired_page_obj.has_next %}
        <a class="w3-button" href="?task=expired&page={{ expired_page_obj.next_page_number }}">{{ expired_page_obj.next_page_number }}</a>
        <a class="w3-button" href="?task=expired&page={{ expired_page_obj.paginator.num_pages }}">&raquo;</a>
      {% endif %}
    </div>
  </div>
{% endif %}
</div>

{% if user.is_authenticated and person.user == user %}
<div id="Task_New" class="w3-container w3-margin w3-responsive tab w3-center" style="display:none">
  <form class="w3-container w3-card-4 w3-theme-14 w3-text-theme w3-center" method="post">
    <h2 class="w3-center w3-animate-top">New Task for <a href="{% url 'planner:person_detail' person.pk %}">{{ person.name }}</a></h2>
    {% csrf_token %}
    <table class="w3-table-all"> 
    {{ form }}
    </table>
    <button class="w3-button w3-section w3-theme w3-ripple w3-round w3-margin">Save</button>
  </form>
</div>
{% endif %}
<script>
  initTabs('Task_Today');
</script>
{% endblock content %}

planner/templates/planner/person_detail.html
{% extends "planner/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<h2>
  Welcome, {{ person.name }}!
</h2>
<div class=w3-row">
  <div class="w3-half w3-container">
    <div class="w3-card w3-theme" >
      <div class="w3-display-container w3-center">
        <img class="w3-image w3-circle w3-center w3-margin" src="{{ person.bio.image }}" style="height:60%; width:60%">
        <h5>{{ person.name }}</h5>
        <h6>{{ person.bio }}</h6>
        <h6>{{ person.email }}</h6>

        <span class="w3-tag w3-xlarge w3-white w3-text-theme w3-margin">{{ person.status }}</span>
        {% if user.is_authenticated and user.person == person %}
        <div class="w3-display-topright">
          <a href="{% url 'planner:person_detail_update_form' person.pk %}">
          <i class='far fa-edit fa-lg'></i>
          </a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="w3-half w3-container w3-responsive">
    <h5>
      <a href="{% url 'planner:task_list' person.pk %}">{{ person.name }}'s Tasks</a>
    at a Glance</h5>
    <table class="w3-table-all w3-hoverable">
      <tr class="w3-theme">
        <th>Title</th>
        <th>Description</th>
        <th>Due</th>
      </tr>
      
        {% for task in tasks_due_today|slice:":3" %}
        <tr>
          <td>{{ task.title }}</td>
          <td title="{{ task.description }}">{{ task.description | truncatechars:20 }}</td>
          <td>
            {{ task.deadline }}
          </td>
        </tr>
        {% empty %}
        <tr>
          <td>None.</td>
          <td>None.</td>
          <td>None.</td>
        </tr>
        {% endfor %}

    </table>
    <h5>
    <a href="{% url 'planner:meeting_list' person.pk %}">{{ person.name }}'s Meetings</a>
    Today</h5>
    <table class="w3-table-all w3-hoverable">
    <tr class="w3-theme">
      <th>Title</th>
      <th>Purpose</th>
      <th>When</th>
      <th>With</th>
    </tr>
    {% for meeting in meetings_today|slice:":3" %}
    <tr>
      <td>{{ meeting.title }}</td>
      <td title="{{ meeting.purpose }}">{{ meeting.purpose | truncatechars:20 }}</td>
      <td>{{ meeting.date }} {{ meeting.time }}</td>
      <td>
        {{ meeting.participants.all|join:', ' }}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td>None.</td>
      <td>None.</td>
      <td>None.</td>
      <td>None.</td>
    </tr>
    {% endfor %}
    </table>
  </div>
</div>
{% endblock content %}